### ISSUE TITLE
Extra dues does not get cleared when mess manager updates dues

### ISSUE THREAD

**Issue by divc13** [Ashu3208/MessAutomationSystem#42]
Consider a situation in which the manager enters an amount greater than the total dues in the dues paid field for a particular student and submits it.
Then, the mess dues are cleared but extra dues are not cleared on the student's side.

The images support the case.
![WhatsApp Image 2023-04-07 at 18 23 35](https://user-images.githubusercontent.com/110289042/230612668-a312669d-1fd1-4c85-878f-b0fddf407e13.jpg)

![image](https://user-images.githubusercontent.com/110289042/230612699-4f5b0a4d-5c60-4556-8608-189c3eee0cef.png)

![WhatsApp Image 2023-04-07 at 18 23 35](https://user-images.githubusercontent.com/110289042/230612725-63272fea-31d1-4104-8e37-092979971755.jpg)

**Comment by chethan58** [comment]
that was intentional because its not included in dues yet.
home page shows
dues which is the total amount user yet to pay till date.
rebate days shows the number of rebate days that are not considered yet in any of user's bills.
extras cost shows the amount of extras user ordered which is not billed yet.
when manager generates the bill above extras cost and rebate days are considered in the bill and later set to 0 , and the total amount of the generated bill will be added to dues .

given the req functionalities the case u mentioned is not an issue . comment if u still have any questions else close issue.

**Comment by divc13** [comment]
@chethan58 why wasn't the software made such that as soon as someone books extras, the amount gets added to the bill. Why do we need to wait for mess manager to enter daily amount to deduct the rebate amount and add the extras amount to students bills? Wouldn't it be better if these things are added directly to the bill?

Also the current system can lead to chaos. Suppose the student wants to clear his dues, possibly for migrating to a different hall. In such case, mess manager knows and generates bill in the morning for instance. In the afternoon, a student books extras and now he wants to have his dues cleared. Since the extras amount has not been added to bill yet, he wont be able to get his dues cleared until the mess manager generates bill again. 

This would be true for different timings as students would clear dues at different times, so mess manager cannot sit whole day and generate bills each second.

Kindly let me know your thoughts over this.

**Comment by chethan58** [comment]
Initially we thought to generate basic mess bill daily i.e.., automatically added to dues everyday and as u said extras is also added to dues as soon as someone books, but due to internal opinion conflicts that was changed to generating bill monthly , also because of some consequence of this change, we felt adding extras as soon as someone books leads to some problem,  but i don't remember what the problem and the consequence are.

And considering the scenario u mentioned i.e.., when students of one hall migrate to another ,manager can generate the bill once when the migrating period begins and once again after everyone left. manager can clear the dues of the students and give no dues to those whoever pays the current dues even for students staying up to week after the bill generated. Because  the bill they will get during the week or so is not very high to not to give no dues to them. Still if u feel the bill for a week is very high manager can generate bill daily once during the migrating period that will make remaining dues even less and also generating bill does not take even a minute so generating once is not much of a task.  also to note this can be solved totally by generating bill two times daily i.e.., once after mess is closed for breakfast and giving no dues  after that instant to the instant  before which mess is open for lunch and second after mess is closed for lunch and giving no dues  starting from that instant up to 5pm . as said earlier this is not much of a task and i think does not lead to chaos.

let me know if u think this has any other problems

**Comment by Ashu3208** [comment]
@divc13 What chethan wants to say that mess bills will be generated monthly and not daily and Generation of the bill of particular month can be done after the dinner timings of last meal of the last day of that month.
Now coming to the point where students are migrating to hostel, students migrate to new hall in a period of a week. So bills can be generated 2-3 days prior to when student started migrating hostel. So for example, the migration starts on 16th of the month, then bills of all students can be generated till 15th. The remaining dues can be then updated on pingala or any other alternate ways can be used.
Also the ways of bill generation can also vary depending on the needs of the hall and it can be customized to satisfy the requirements of the hall. Please close the issue if satisfied.
